services:  
  backend:
    build:
      context: "."
      dockerfile: "./WebAPI/Dockerfile"
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - database
      - minio 
      - redis


  database:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: nippo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - 5435:5432
    volumes:
      - db-data:/var/lib/postgresql/data
  

  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: rootUser
      MINIO_ROOT_PASSWORD: rootPassword
      MINIO_BROWSER_REDIRECT_URL: http://localhost/minio-console/
    volumes:
      - minio-storage:/data


  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - redis-data:/data
    restart: always
    ports:
      - "6379:6379"


  proxy:
    image: nginx:latest
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - minio

volumes:
  redis-data:
  minio-storage:
  db-data: