version: '3.4'

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: nippo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 231
    ports:
      - 5435:5432
